import { FacialPalace } from "../types/tianji";

export const FACIAL_PALACES: FacialPalace[] = [
  {
    id: "forehead",
    name: "天庭 / 官禄宫与父母宫 (额头)",
    location: "发际线以下至印堂上方区域",
    correspondsTo: "紫微斗数之父母宫、官禄宫与早年运势（15-30岁）",
    auspiciousSigns: "额头饱满圆润、光明如镜、无恶痣杂纹、发际线整齐开阔",
    inauspiciousSigns: "额头凹陷窄小、横纹截断、晦暗发青、疤痕恶痣",
    tianjiInsight: "倪师论相：天庭高耸饱满者，祖荫丰厚，受父母师长庇佑，早年科名得利，适合仕途大企业及学术登顶。若额头发黑发暗，需防官非与长辈健康关口。",
  },
  {
    id: "yintang",
    name: "印堂 / 命宫 (两眉之间)",
    location: "两眉毛正中央，山根之上",
    correspondsTo: "紫微斗数之命宫、当下心境与近三个月吉凶总枢纽",
    auspiciousSigns: "宽容二指、平满光润、色泽红黄明亮、紫气东来",
    inauspiciousSigns: "两眉紧锁交加、悬针纹深刺、色泽晦暗青黑、凹陷狭窄",
    tianjiInsight: "天纪核心关窍：印堂为一身之神明汇聚处。印堂红黄者大运将至，万事可成；印堂发黑发青者，有灾厄临头（君子问祸不问福），宜立刻止步息事宁人。",
  },
  {
    id: "eyes",
    name: "双目 / 心性神韵 (眼神定善恶)",
    location: "左右眼眸与瞳孔神采",
    correspondsTo: "紫微斗数之身宫心性、贵贱大格局（35-40岁）",
    auspiciousSigns: "黑白分明、神藏不露、清澈坚定、威严含仁、光彩内敛",
    inauspiciousSigns: "四白眼、三角眼、眼神游移闪烁、血丝贯瞳、凶光暴露",
    tianjiInsight: "倪师传神论相：看相之最高境界在于‘看神’。眼神定者，虽处逆境亦能翻盘；眼神散乱露光者，得运亦难久长。眼神慈悲坚定者成大器。",
  },
  {
    id: "eyebrows",
    name: "保寿官 / 兄弟宫与人际 (眉毛)",
    location: "眼睛上方眉弓骨",
    correspondsTo: "紫微斗数之兄弟宫、交友宫及肝胆气血（31-34岁）",
    auspiciousSigns: "眉秀而长、顺理贴肉、根根见肉、高居额上、过眼角",
    inauspiciousSigns: "杂乱逆生、断眉残眉、浓密压眼、旋毛倒长",
    tianjiInsight: "天纪精解：眉毛是肝胆之苗、人际贵人与兄弟合伙之晴雨表。眉顺者兄弟齐心合伙发财；眉乱或断裂者慎防朋友背叛与合伙破裂。",
  },
  {
    id: "nose",
    name: "审辨官 / 财帛宫与疾厄宫 (鼻子与山根)",
    location: "山根、年寿至鼻头准头与左右鼻翼（兰台廷尉）",
    correspondsTo: "紫微斗数之财帛宫、疾厄宫及中年大运（41-50岁）",
    auspiciousSigns: "山根丰隆通鼻梁、准头圆厚如胆、鼻翼饱满有收、色泽黄亮",
    inauspiciousSigns: "山根低陷折断、鼻梁起节露骨、鼻孔仰露（朝天鼻）、准头赤红长痘",
    tianjiInsight: "倪师论财帛：准头有肉心无毒，鼻孔藏风财库丰。山根折断者中年必有重创（疾厄或破产）；鼻翼薄弱者宜留流动现金或购入不动产避险。",
  },
  {
    id: "tear_trough",
    name: "男女宫 / 卧蚕与子女宫 (眼下下眼睑)",
    location: "下眼皮隆起如蚕蛹处",
    correspondsTo: "紫微斗数之子女宫与肾气精血",
    auspiciousSigns: "饱满润泽、微微隆起如卧蚕、气色明润微粉",
    inauspiciousSigns: "干瘪发黑、眼袋下垂发青、有深陷井字纹或恶痣",
    tianjiInsight: "天纪医理相参：眼下为三阴三阳之所，主管肾水生殖与子女缘。卧蚕明亮者子孙贤孝有大出息；卧蚕深黑干枯者需调理肾精与作息。",
  },
  {
    id: "chin",
    name: "地阁 / 奴仆宫与田宅晚运 (下巴与腮骨)",
    location: "嘴唇下方至下颌骨区域",
    correspondsTo: "紫微斗数之田宅宫、仆役宫及晚年运势（60岁以后）",
    auspiciousSigns: "地阁方圆饱满、朝拱鼻头、腮骨有肉包覆、双下巴纳福",
    inauspiciousSigns: "尖削后缩、腮骨横张（反骨）、下巴无肉见骨",
    tianjiInsight: "天纪晚运法则：天庭主早年，地阁主晚运与不动产。地阁饱满丰厚者，晚年安享儿孙绕膝与丰厚祖业，下属忠诚拱卫。",
  },
];
