import { HexagramData, TrigramName, HeavenlyStem, EarthlyBranch, Gender } from "../types/tianji";
import { calculateTianjiNumerology, getHexagramSymbol, FourPillarsNumerology } from "./tianjiIchingNumerology";
import { RENJIAN_DAO_64_DATABASE, getRenjianDaoDetail } from "./renjianDaoData";

export const TRIGRAM_SYMBOLS: Record<TrigramName, string> = {
  "乾": "☰",
  "坤": "☷",
  "震": "☳",
  "巽": "☴",
  "坎": "☵",
  "离": "☲",
  "艮": "☶",
  "兑": "☱",
  "中": "☯",
};

export const TRIGRAM_ELEMENTS: Record<TrigramName, string> = {
  "乾": "天 / 金",
  "坤": "地 / 土",
  "震": "雷 / 木",
  "巽": "风 / 木",
  "坎": "水 / 水",
  "离": "火 / 火",
  "艮": "山 / 土",
  "兑": "泽 / 金",
  "中": "太极 / 土",
};

export const ALL_64_HEXAGRAMS_BRIEF: {
  number: number;
  name: string;
  pinyin: string;
  upperTrigram: TrigramName;
  lowerTrigram: TrigramName;
  symbol: string;
  judgment: string;
  image: string;
  tianjiContext: string;
  actionGuidance: string;
  businessGuidance: string;
  relationshipGuidance: string;
  healthGuidance: string;
}[] = [
  {
    number: 1,
    name: "乾为天",
    pinyin: "Qián Wéi Tiān",
    upperTrigram: "乾",
    lowerTrigram: "乾",
    symbol: "䷀",
    judgment: "元亨利贞。天行健，君子以自强不息。",
    image: "六阳纯正，刚健中正，万物资始，乃统天。",
    tianjiContext: "《天纪》论乾卦：纯阳之刚，万物之始。身处乾位，代表大势已成、统帅全局。初九潜龙勿用，九二见龙在田，九五飞龙在天，上九亢龙有悔。知进退存亡方显至尊乾道。",
    actionGuidance: "【以果决行】：当前宜果敢树立权威与清晰战略，但需根据所处阶段定位（潜伏/现身/登顶/防亢），切忌独断专行导致孤立。",
    businessGuidance: "战略主导，适合创办企业、开拓全新宏大版图，聚拢顶尖人才。",
    relationshipGuidance: "刚正专一，居一家之主宰，需多听取配偶意见以阴阳相济。",
    healthGuidance: "主头部、心脑血管及大肠，注意血压与过劳休养。",
  },
  {
    number: 2,
    name: "坤为地",
    pinyin: "Kūn Wéi Dì",
    upperTrigram: "坤",
    lowerTrigram: "坤",
    symbol: "䷁",
    judgment: "元亨，利牝马之贞。地势坤，君子以厚德载物。",
    image: "纯阴柔顺，包容万物，顺承天道，德合无疆。",
    tianjiContext: "《天纪》论坤卦：柔顺而动，以静制动。坤道强调‘后得主’——不抢先出头，而在后方默默蓄积力量、承载万物。若履霜，坚冰至，见微知著也。",
    actionGuidance: "【以果决行】：以退为进，深居修德，配合主力行动，不宜盲目争抢首发锋芒，重在长期积累。",
    businessGuidance: "适合幕僚、供应链、重资产运营、后台支持与长线资产持有。",
    relationshipGuidance: "母仪天下，温柔贤淑，包容理解是维系家庭之核心基石。",
    healthGuidance: "主脾胃、消化系统及腹部妇科，宜温养脾土，忌生冷寒凉。",
  },
  {
    number: 3,
    name: "水雷屯",
    pinyin: "Shuǐ Léi Zhūn",
    upperTrigram: "坎",
    lowerTrigram: "震",
    symbol: "䷂",
    judgment: "元亨利贞，勿用有攸往，利建侯。",
    image: "云雷交合，万物始萌，动于险中，慎始开创。",
    tianjiContext: "《天纪》论屯卦：物之初生，如婴儿出母胎，万事开头难。动在险中，不可轻举妄动，宜广招贤能、建立制度，以贵下贱大得民心。",
    actionGuidance: "【以果决行】：创业初期切勿孤军深入，当务之急是招募核心班底、搭建规范架构，稳步破冰。",
    businessGuidance: "早期初创项目，资金与市场尚在摸索，宜低调蓄势，抱团取暖。",
    relationshipGuidance: "感情刚确立或处于考验期，需真诚耐心沟通，不可操之过急。",
    healthGuidance: "注意肾水与肝木疏泄，避免过度焦虑引发失眠脱发。",
  },
  {
    number: 4,
    name: "山水蒙",
    pinyin: "Shān Shuǐ Méng",
    upperTrigram: "艮",
    lowerTrigram: "坎",
    symbol: "䷃",
    judgment: "亨。匪我求童蒙，童蒙求我。初筮告，再三渎，渎则不告。利贞。",
    image: "山下出泉，草木蒙昧，去蔽启智，果行育德。",
    tianjiContext: "《天纪》论蒙卦：启蒙发蒙之道。人处愚蒙不知所措之时，必须虚心求教于明师。教蒙之法先立刑规知所畏惧，而后施以仁义德行。",
    actionGuidance: "【以果决行】：承认自身局限，放下虚荣，主动拜名师、求高人指点，切忌不懂装懂盲目乱闯。",
    businessGuidance: "进入未知新领域，必须先进行市场调研或聘请资深顾问，不可盲目砸钱。",
    relationshipGuidance: "感情中多一些耐心引导与包容，少一些无谓的指责争辩。",
    healthGuidance: "注意耳鸣、耳疾与泌尿消化问题，保持作息规律。",
  },
  {
    number: 5,
    name: "水天需",
    pinyin: "Shuǐ Tiān Xū",
    upperTrigram: "坎",
    lowerTrigram: "乾",
    symbol: "䷄",
    judgment: "有孚，光亨，贞吉。利涉大川。",
    image: "云上于天，密云不雨，饮食宴乐，从容待时。",
    tianjiContext: "《天纪》论需卦：内刚健而外临险，知待之时也。天下英雄能忍者成大事，在等待中养精蓄锐，饮食宴乐和其心志，待天时一到，直涉大川！",
    actionGuidance: "【以果决行】：时机未成熟前耐心等待，切忌心浮气躁强行推行；在等待期完善产品与团队。",
    businessGuidance: "大单或重大合作尚在酝酿期，保持高层良好互动，不急于催促签约。",
    relationshipGuidance: "感情水到渠成，给彼此空间与时间，切忌夺命连环逼婚。",
    healthGuidance: "宜规律饮食，调养脾胃与血液循环，防过度熬夜耗气。",
  },
  {
    number: 6,
    name: "天水讼",
    pinyin: "Tiān Shuǐ Sòng",
    upperTrigram: "乾",
    lowerTrigram: "坎",
    symbol: "䷅",
    judgment: "有孚窒惕，中吉，终凶。利见大人，不利涉大川。",
    image: "天上水下，背道而驰，争端既起，作事谋始。",
    tianjiContext: "《天纪》论讼卦：内险外健，争讼之源。凡诉讼无赢家，终必致凶。作事谋始，在起步之时把合同契约与利益分配合情合理厘清，方能无讼。",
    actionGuidance: "【以果决行】：有争议宜及早和解调解，不可意气用事打消耗战官司；迅速寻求权威公证人裁决。",
    businessGuidance: "严格审核商业合同条款与知识产权，防合作方暗中使绊或反目成仇。",
    relationshipGuidance: "夫妻口角升级前主动退让一步，切莫因小事升级为法庭诉讼。",
    healthGuidance: "肝阳上亢，情绪激动易诱发高血压与心绞痛，宜静心调摄。",
  },
  {
    number: 7,
    name: "地水师",
    pinyin: "Dì Shuǐ Shī",
    upperTrigram: "坤",
    lowerTrigram: "坎",
    symbol: "䷆",
    judgment: "贞，丈人吉，无咎。地中有水，容民畜众。",
    image: "地下聚水，行险而顺，统军出征，专任大将。",
    tianjiContext: "《天纪》论师卦：兵者国之大事，出师必有名，且必须任用威望德才兼备之‘丈人’为主帅，将权专一，君主不疑，方能克敌制胜。",
    actionGuidance: "【以果决行】：攻坚克难期必须统一指挥权，严明纪律，重用一线实干老将，杜绝多头领导。",
    businessGuidance: "抢占战略要塞与关键客户，集中优势兵力单点突破，不搞分散投资。",
    relationshipGuidance: "家庭内部建立规则界限，关键大事由主心骨统筹决策。",
    healthGuidance: "注意腰肾亏损与筋骨劳损，加强体能锻炼。",
  },
  {
    number: 8,
    name: "水地比",
    pinyin: "Shuǐ Dì Bǐ",
    upperTrigram: "坎",
    lowerTrigram: "坤",
    symbol: "䷇",
    judgment: "吉。原筮元永贞，无咎。不宁方来，后夫凶。",
    image: "水附于地，亲密相辅，建万国，亲诸侯。",
    tianjiContext: "《天纪》论比卦：亲和亲比之道。众志成城，互利共赢。相比之道贵在主动诚恳，若迟疑不决成为‘后夫’，则错失良机必招凶咎。",
    actionGuidance: "【以果决行】：主动出击构建战略联盟，结识高价值伙伴，诚信合作，抢占合作先机。",
    businessGuidance: "产业链上下游强强联合，实施股权激励与合伙人制度凝聚人心。",
    relationshipGuidance: "主动表达关心与爱意，夫妻同舟共济，感情日笃。",
    healthGuidance: "水土相合，体态安和，多饮温开水促进代谢。",
  },
  {
    number: 9,
    name: "风天小畜",
    pinyin: "Fēng Tiān Xiǎo Xù",
    upperTrigram: "巽",
    lowerTrigram: "乾",
    symbol: "䷈",
    judgment: "亨。密云不雨，自我西郊。风行天上，君子以懿文德。",
    image: "风行天上，蓄势待发，以柔制刚，积小成大。",
    tianjiContext: "《天纪》论小畜：小有蓄积，外柔内刚。以柔顺之道涵养刚健之才，在细节上积攒实力与文才修养，等待阴阳和畅降甘霖。",
    actionGuidance: "【以果决行】：注重微小细节优化与日常现金流积累，以温和柔顺手段协调各方关系。",
    businessGuidance: "中小企业微创新与精细化运营，不宜盲目重资产盲目扩张。",
    relationshipGuidance: "以柔克刚，多关怀对方情绪，小摩擦宜温和化解。",
    healthGuidance: "防呼吸道风邪与肺经干燥，宜多润肺生津。",
  },
  {
    number: 10,
    name: "天泽履",
    pinyin: "Tiān Zé Lǚ",
    upperTrigram: "乾",
    lowerTrigram: "兑",
    symbol: "䷉",
    judgment: "履虎尾，不咥人，亨。上天下泽，辩上下，定民志。",
    image: "如履虎尾，敬慎戒惧，循规蹈矩，行危无咎。",
    tianjiContext: "《天纪》论履卦：礼也。伴君如伴虎，处险境而不被吞噬，全靠知礼敬慎、辨明尊卑。心中戒惧存敬畏，虽涉险地亦能安然化险为夷。",
    actionGuidance: "【以果决行】：面对强权客户或严苛监管，严格遵守行业规矩与法律红线，态度谦卑恭敬。",
    businessGuidance: "合规审查第一，不可打法律擦边球，注意与行业巨头保持礼貌界限。",
    relationshipGuidance: "尊重对方家庭长辈，言行举止得体大方，切忌无理冒犯。",
    healthGuidance: "注意咽喉口腔与胸部神经，防焦虑失眠。",
  },
  {
    number: 11,
    name: "地天泰",
    pinyin: "Dì Tiān Tài",
    upperTrigram: "坤",
    lowerTrigram: "乾",
    symbol: "䷊",
    judgment: "小往大来，吉亨。天地交而万物通，上下交而其志同。",
    image: "天气下降，地气上升，天地交泰，万物亨通。",
    tianjiContext: "《天纪》论泰卦：天地相交，人间最吉之大局。君臣同心，夫妻和睦，万事顺遂。阳进阴退，君子道长，小人道消。包荒用冯河，大展宏图！",
    actionGuidance: "【以果决行】：全面进攻与扩张的黄金期！顺势而为，大举投入，乘胜追击，同时建立制度长效机制。",
    businessGuidance: "商务谈判顺遂，项目盈利丰厚，企业上下凝聚力空前高涨。",
    relationshipGuidance: "夫妻琴瑟和鸣，家和万事兴，若夫妻同住西南坤位即成此泰卦大局！",
    healthGuidance: "气血充盈，身心泰然，保持规律作息即可百病不生。",
  },
  {
    number: 12,
    name: "天地否",
    pinyin: "Tiān Dì Pǐ",
    upperTrigram: "乾",
    lowerTrigram: "坤",
    symbol: "䷋",
    judgment: "否之匪人，不利君子贞，大往小来。天地不交，否。",
    image: "天升地降，隔绝不通，君子道消，小人道长。",
    tianjiContext: "《天纪》论否卦：大往小来，闭塞不通。此时正道不行，小人得势。君子当以俭德辟难，不可荣以禄，绝不可恋栈名位，退守静观待变。",
    actionGuidance: "【以果决行】：立刻踩刹车！停止冒险扩张与重大投资，清理内部小人阻隔，保存现金流与实力。",
    businessGuidance: "市场环境恶劣或合作方缺乏诚信，严控开支，不盲目接大项目。",
    relationshipGuidance: "沟通严重受阻，同床异梦，切忌硬碰硬激化矛盾引发离婚。",
    healthGuidance: "气滞血瘀，肝郁脾虚，需格外防范大病缠身与手术血光。",
  },
  {
    number: 13,
    name: "天火同人",
    pinyin: "Tiān Huǒ Tóng Rén",
    upperTrigram: "乾",
    lowerTrigram: "离",
    symbol: "䷌",
    judgment: "同人于野，亨。利涉大川，利君子贞。天下大同。",
    image: "火性炎上，与天同道，大公无私，通天下志。",
    tianjiContext: "《天纪》论同人：大公无私，大同之世。走出狭隘宗族朋党，在旷野之中与天下英豪志同道合。外健内明，二人同心其利断金！",
    actionGuidance: "【以果决行】：摒弃门户私见，广结善缘，与行业顶尖伙伴合伙创业共赢天下。",
    businessGuidance: "适合合伙制企业、平台型生态构建与全国性业务推广。",
    relationshipGuidance: "以开放包容之心对待伴侣，共同追求高远的人生价值观。",
    healthGuidance: "心火旺盛，注意眼部疲劳与心脑血管保养。",
  },
  {
    number: 14,
    name: "火天大有",
    pinyin: "Huǒ Tiān Dà Yǒu",
    upperTrigram: "离",
    lowerTrigram: "乾",
    symbol: "䷍",
    judgment: "元亨。火在天上，大有。君子以遏恶扬善，顺天休命。",
    image: "日丽中天，光明普照，万物资盛，富甲天下。",
    tianjiContext: "《天纪》论大有：日丽中天，富强鼎盛。柔居尊位而众阳应之。遏恶扬善，顺天休命。富有而不骄奢，自天祐之，吉无不利！",
    actionGuidance: "【以果决行】：顺应时代风口果断做大做强，同时兼济天下、回馈社会以固福报。",
    businessGuidance: "企业进入高速扩张与规模盈利期，注重品牌美誉度与社会责任。",
    relationshipGuidance: "物质充盈，家庭和美，注意防范因外界诱惑产生感情波澜。",
    healthGuidance: "精力充沛，注意防燥热与眼疾，适量清润排毒。",
  },
  {
    number: 15,
    name: "地山谦",
    pinyin: "Dì Shān Qiān",
    upperTrigram: "坤",
    lowerTrigram: "艮",
    symbol: "䷎",
    judgment: "亨，君子有终。地中有山，裒多益寡，称物平施。",
    image: "山高居地，内高外卑，劳谦君子，万民臣服。",
    tianjiContext: "《天纪》论谦卦：地中有山，崇高而处卑下。天道亏盈而益谦，地道变盈而流谦，鬼神害盈而福谦，人道恶盈而好谦。唯谦德可保安享尊荣至终！",
    actionGuidance: "【以果决行】：功高不自傲，位高不弄权；以谦逊姿态对待同事客户，广获拥戴。",
    businessGuidance: "在行业领头羊位置保持低调务实，多做公益与普惠，杜绝垄断恶名。",
    relationshipGuidance: "互相体谅，遇事多替对方着想，谦让是消弭家庭矛盾之神药。",
    healthGuidance: "脾胃安泰，骨骼强健，心态平和长寿之相。",
  },
  {
    number: 16,
    name: "雷地豫",
    pinyin: "Léi Dì Yù",
    upperTrigram: "震",
    lowerTrigram: "坤",
    symbol: "䷏",
    judgment: "利建侯行师。雷出地奋，作乐崇德，殷荐上帝。",
    image: "雷动地上，和乐顺畅，顺理而动，万物同欢。",
    tianjiContext: "《天纪》论豫卦：动而顺理，万民和悦。先王作乐崇德以配祖考。处豫之时，最忌沉溺酒色安逸，必须介于石不终日，居安思危方能长乐。",
    actionGuidance: "【以果决行】：团队士气高涨时果断发起战役攻坚，但严防庆功宴上的懈怠与纵欲。",
    businessGuidance: "品牌公关、文娱传媒、节庆营销等大获丰收，顺势拓展新渠道。",
    relationshipGuidance: "感情甜蜜温馨，多安排浪漫出行，但不可玩物丧志。",
    healthGuidance: "防暴饮暴食伤脾胃，少饮烈酒，注意肝胆解毒。",
  },
  {
    number: 17,
    name: "泽雷随",
    pinyin: "Zé Léi Suí",
    upperTrigram: "兑",
    lowerTrigram: "震",
    symbol: "䷐",
    judgment: "随，元亨利贞，无咎。泽中有雷，随时而动；君子以向晦入宴息。",
    image: "泽中有雷，雷动则泽随，与时俱进，从善如流。",
    tianjiContext: "《天纪》论随卦：随时之义大矣哉。处随之时，贵在审时度势、择善而从，不可固守己见泥古不化。所随之人正，则事半功备。",
    actionGuidance: "【以果决行】：顺应大势与良机，主动追随明师贤友；但须辨明所随之人是否正派，随善不随恶。",
    businessGuidance: "合作加盟、借力打力之象，宜跟随行业龙头或被并购整合，共享渠道资源。",
    relationshipGuidance: "感情中贵在同心同向，彼此迁就配合，随缘而不强求。",
    healthGuidance: "主肝胆与脾胃调和，作息随四时，忌逆时熬夜伤肝。"
  },
  {
    number: 18,
    name: "山风蛊",
    pinyin: "Shān Fēng Gǔ",
    upperTrigram: "艮",
    lowerTrigram: "巽",
    symbol: "䷑",
    judgment: "蛊，元亨，利涉大川。先甲三日，后甲三日。山下有风，振民育德。",
    image: "山下有风，积弊成蛊，坏极而当治，拨乱反正。",
    tianjiContext: "《天纪》论蛊卦：山下有风，积弊成蛊。此时必须大刀阔斧整顿父辈遗留之败坏，先甲三日谋始，后甲三日验终。",
    actionGuidance: "【以果决行】：发现组织与关系中的积弊，当痛下决心整治清理，前谋后验，不可姑息养奸。",
    businessGuidance: "企业反腐、流程再造、并购后整合的整顿期，破旧立新方有生机。",
    relationshipGuidance: "家庭或感情中的旧疮疤须坦诚面对疗愈，掩盖只会溃烂。",
    healthGuidance: "主虫病、脾胃积滞、慢性中毒，宜排毒调理、清肠养胃。"
  },
  {
    number: 19,
    name: "地泽临",
    pinyin: "Dì Zé Lín",
    upperTrigram: "坤",
    lowerTrigram: "兑",
    symbol: "䷒",
    judgment: "临，元亨利贞，至于八月有凶。泽上有地，教思无穷。",
    image: "泽上有地，居高临下，阳长阴消，盛极防衰。",
    tianjiContext: "《天纪》论临卦：临者监临也。阳长阴消，阳气渐盛之吉象，然八月阴返有凶，须居安思危、厚下安宅。",
    actionGuidance: "【以果决行】：身处上升期宜亲临一线、体察下情，恩威并施；盛时预留退路，防八月之凶。",
    businessGuidance: "市场开拓、管理下沉、亲自督战可成大事，但勿盲目扩张过度。",
    relationshipGuidance: "以包容关怀之心临家，长者垂范、潜移默化最吉。",
    healthGuidance: "主脾胃充实，但防过补生湿，宜运动代谢。"
  },
  {
    number: 20,
    name: "风地观",
    pinyin: "Fēng Dì Guān",
    upperTrigram: "巽",
    lowerTrigram: "坤",
    symbol: "䷓",
    judgment: "观，盥而不荐，有孚颙若。风行地上，省方观民。",
    image: "风行地上，周览万物，以德化人，不尚虚文。",
    tianjiContext: "《天纪》论观卦：风行地上，周览万物。在上者当如祭祀前之诚洁，以诚信感化天下，不尚虚文浮礼。",
    actionGuidance: "【以果决行】：先观察大局与人心向背，以身作则树立典范，不妄动而观其衅。",
    businessGuidance: "市场调研、品牌种草、树立企业价值观的积累期，重口碑轻促销。",
    relationshipGuidance: "多观察对方真实品性而非表面，以诚相待方能长久。",
    healthGuidance: "主神经系统与气机疏散，宜静坐观心、调息安神。"
  },
  {
    number: 21,
    name: "火雷噬嗑",
    pinyin: "Huǒ Léi Shì Kè",
    upperTrigram: "离",
    lowerTrigram: "震",
    symbol: "䷔",
    judgment: "噬嗑，亨。利用狱。雷电合章，明罚敕法。",
    image: "颐中有物，必啮而后合，雷电交击，明断梗阻。",
    tianjiContext: "《天纪》论噬嗑：颐中有物，必啮而后合。遇阻碍梗阻，必须果决咬破、明断是非，方能畅通。",
    actionGuidance: "【以果决行】：遭遇纠纷壁垒，当据理依法坚决清除，不可和稀泥姑息养奸。",
    businessGuidance: "打假维权、反垄断、清理违约合作方，法律手段必要且正当。",
    relationshipGuidance: "沟通中的硬梗须直面拆解，回避只会越积越深。",
    healthGuidance: "主口腔牙齿、消化道梗阻，宜及时就医勿拖延。"
  },
  {
    number: 22,
    name: "山火贲",
    pinyin: "Shān Huǒ Bì",
    upperTrigram: "艮",
    lowerTrigram: "离",
    symbol: "䷕",
    judgment: "贲，亨。小利有攸往。山下有火，文明以止。",
    image: "山下有火，质文相饰，修饰得宜，本质不丧。",
    tianjiContext: "《天纪》论贲卦：山下有火，文明以止。贲者饰也，质胜文则野，文胜质则史，修饰得宜而本质不丧方为人文之美。",
    actionGuidance: "【以果决行】：适度包装形象与品牌，但华而不实终必败，重内涵轻浮华。",
    businessGuidance: "产品外观、品牌视觉、公关形象升级的良机，小利有攸往。",
    relationshipGuidance: "感情需要仪式感与外在经营，但真情才是根本。",
    healthGuidance: "主面色气血、皮肤毛发，宜调养气血、忌过度医美。"
  },
  {
    number: 23,
    name: "山地剥",
    pinyin: "Shān Dì Bō",
    upperTrigram: "艮",
    lowerTrigram: "坤",
    symbol: "䷖",
    judgment: "剥，不利有攸往。山附于地，厚下安宅。",
    image: "山附于地，阴盛剥阳，正气剥落，蛰伏自保。",
    tianjiContext: "《天纪》论剥卦：山附于地，阴盛剥阳。此时小人得志、正气剥落，不利有所往。须体恤底层、稳固根基以止崩。",
    actionGuidance: "【以果决行】：大势衰退期立即停止扩张，蛰伏自保，厚植根基，等待阳回复生。",
    businessGuidance: "行业下行、资金链紧张，宜收缩战线、保全现金、不接大单。",
    relationshipGuidance: "关系剥离瓦解时勿强留，体面退场保存颜面。",
    healthGuidance: "主气血衰败、皮肤溃损，宜静养固本，忌手术冒险。"
  },
  {
    number: 24,
    name: "地雷复",
    pinyin: "Dì Léi Fù",
    upperTrigram: "坤",
    lowerTrigram: "震",
    symbol: "䷗",
    judgment: "复，亨。出入无疾，朋来无咎。七日来复，利有攸往。雷在地中，复见天地之心。",
    image: "雷在地中，一阳来复，阴极阳返，生机重现。",
    tianjiContext: "《天纪》论复卦：雷在地中，一阳来复。七日来复，天行也。阴极阳返，生机重现，反复其道终而复始，乃天地之心。",
    actionGuidance: "【以果决行】：否极泰来、触底反弹的转折点，抓住一线生机果断回归正道与初心。",
    businessGuidance: "业务触底反弹、离职创业或重启项目的最佳窗口，朋来无咎。",
    relationshipGuidance: "感情破镜重圆、关系修复的吉期，真诚可挽回。",
    healthGuidance: "主元气复苏、大病初愈之调养期，早睡养阳最为关键。"
  },
  {
    number: 25,
    name: "天雷无妄",
    pinyin: "Tiān Léi Wú Wàng",
    upperTrigram: "乾",
    lowerTrigram: "震",
    symbol: "䷘",
    judgment: "元亨利贞。其匪正有眚，不利有攸往。",
    image: "天下雷行，物与无妄。先王以茂对时，育万物。",
    tianjiContext: "《天纪》论无妄：天下雷动，顺应天然，绝无虚妄。在阳宅中，长男居西北乾位即成天雷无妄卦，代表少年老成、提早当家掌权、极具创业魄力。",
    actionGuidance: "【以果决行】：恪守正道，脚踏实地，凭真才实学破局，切不可走捷径或抱侥幸投机心理。",
    businessGuidance: "创业起步迅猛，青年才俊大显身手，注重合规经营。",
    relationshipGuidance: "为人刚正有担当，对待感情认真不欺。",
    healthGuidance: "精力旺盛但需防劳累过度引发神经衰弱。",
  },
  {
    number: 26,
    name: "山天大畜",
    pinyin: "Shān Tiān Dà Xù",
    upperTrigram: "艮",
    lowerTrigram: "乾",
    symbol: "䷙",
    judgment: "大畜，利贞，不家食吉，利涉大川。天在山中，多识前言往行。",
    image: "天在山中，大畜德业，厚积薄发，养贤蓄能。",
    tianjiContext: "《天纪》论大畜：天在山中，大畜之象。刚健笃实，辉光日新。此时宜蓄积才德、广览前言往行，养精蓄锐以待大用，不急于求成。",
    actionGuidance: "【以果决行】：潜心学习积累、储备人才与资本，时机未到不轻易出击，厚积方能薄发。",
    businessGuidance: "研发沉淀、人才梯队建设、长期资产持有的蓄力期，利涉大川。",
    relationshipGuidance: "感情宜先立业后成家，或共同成长蓄德，勿急于求成。",
    healthGuidance: "主脾胃与筋骨强健，宜进补蓄养，但防积滞肥胖。"
  },
  {
    number: 27,
    name: "山雷颐",
    pinyin: "Shān Léi Yí",
    upperTrigram: "艮",
    lowerTrigram: "震",
    symbol: "䷚",
    judgment: "颐，贞吉。观颐，自求口实。山下有雷，慎言语节饮食。",
    image: "山下有雷，颐养之道，慎言节食，养正为吉。",
    tianjiContext: "《天纪》论颐卦：山下有雷，颐养之象。颐者养也，观其所养、自求口实。养德养身皆贵以正，言语饮食不可不节。",
    actionGuidance: "【以果决行】：专注自我修养与健康管理，谨言慎行，量入为出，养正避邪。",
    businessGuidance: "养生、餐饮、健康产业利好；亦主静守本业、蓄势以待。",
    relationshipGuidance: "家庭颐养和睦，照顾老小，言语温和最吉。",
    healthGuidance: "主食道肠胃、口腔，宜规律饮食、戒贪嘴，养生关键卦。"
  },
  {
    number: 28,
    name: "泽风大过",
    pinyin: "Zé Fēng Dà Guò",
    upperTrigram: "兑",
    lowerTrigram: "巽",
    symbol: "䷛",
    judgment: "大过，栋桡，利有攸往，亨。泽灭木，独立不惧。",
    image: "泽灭于木，大过非常，独立不惧，遁世无闷。",
    tianjiContext: "《天纪》论大过：泽灭木，大过之象。阳盛阴衰，非常之时。栋梁将挠，必赖非常之人行非常之事，独立不惧、遁世无闷。",
    actionGuidance: "【以果决行】：身临非常变局，须有担当巨任的魄力，敢于破格任用非常之人。",
    businessGuidance: "重大重组、孤注一掷的转折决策期，成则大成，败则大过。",
    relationshipGuidance: "感情中的巨大考验，需一方独立承担，不离不弃方过此关。",
    healthGuidance: "主栋梁之疾、脊柱神经，防过劳垮塌，宜及时诊治。"
  },
  {
    number: 29,
    name: "坎为水",
    pinyin: "Kǎn Wéi Shuǐ",
    upperTrigram: "坎",
    lowerTrigram: "坎",
    symbol: "䷜",
    judgment: "习坎，有孚，维心亨，行有尚。水洊至，常德行习教事。",
    image: "水洊至，重险叠坎，心诚则亨，习坎有常。",
    tianjiContext: "《天纪》论坎卦：习坎，重险也。水流而不盈，行险而不失其信。处重重险难，唯以刚中之心、诚信之德方能亨通，行有尚。",
    actionGuidance: "【以果决行】：深陷连续困境，切勿慌乱冒进，以诚信与定力逐步脱险，行险有常。",
    businessGuidance: "现金流断裂、连环危机期，须守信用、稳现金流、步步为营。",
    relationshipGuidance: "感情至暗时刻，以诚相待共渡难关，忌互相指责。",
    healthGuidance: "主肾水、泌尿、心血管，险疾缠身，宜静养防意外。"
  },
  {
    number: 30,
    name: "离为火",
    pinyin: "Lí Wéi Huǒ",
    upperTrigram: "离",
    lowerTrigram: "离",
    symbol: "䷝",
    judgment: "离，利贞，亨。畜牝牛，吉。明两作，继明照四方。",
    image: "明两作离，附丽光明，柔顺中正，继明四方。",
    tianjiContext: "《天纪》论离卦：明两作，离也。火之附物而后明，人必有所丽而后成。大人以继明照于四方，柔丽乎中正则吉。",
    actionGuidance: "【以果决行】：借势光明平台与贵人，以柔顺中正之道依附成事，持续发光发热。",
    businessGuidance: "文化传媒、品牌照明、教育培训正当旺，畜牝牛（守柔顺）方吉。",
    relationshipGuidance: "感情中相互依附温暖，柔顺包容最长久。",
    healthGuidance: "主心火、眼睛，宜清润降火，防心浮气躁。"
  },
  {
    number: 31,
    name: "泽山咸",
    pinyin: "Zé Shān Xián",
    upperTrigram: "兑",
    lowerTrigram: "艮",
    symbol: "䷞",
    judgment: "咸，亨，利贞，取女吉。山上有泽，以虚受人。",
    image: "山上有泽，感应相通，虚心相与，男女相悦。",
    tianjiContext: "《天纪》论咸卦：山上有泽，咸也。咸者感也，以虚受人。少男少女相感，自然流露，不假思虑，天地万物之情可见。",
    actionGuidance: "【以果决行】：以真诚虚怀感应他人，顺势建立情感与合作关系，取女（结盟）吉。",
    businessGuidance: "品牌与用户情感连接、年轻化营销、新伙伴结缘的良机。",
    relationshipGuidance: "婚恋正缘卦，真诚相感最吉，勿功利算计。",
    healthGuidance: "主心神感应、神经系统，宜放松交感，忌紧张闭塞。"
  },
  {
    number: 32,
    name: "雷风恒",
    pinyin: "Léi Fēng Héng",
    upperTrigram: "震",
    lowerTrigram: "巽",
    symbol: "䷟",
    judgment: "恒，亨，无咎，利贞，利有攸往。雷风，立不易方。",
    image: "雷风相与，恒久不已，立不易方，长久之道。",
    tianjiContext: "《天纪》论恒卦：雷风相与，恒也。恒者久也，立不易方。夫妇父子君臣之道皆贵有恒，然恒中亦有变，不可执一不通。",
    actionGuidance: "【以果决行】：守正有恒、长期主义，但须审时微调，不可固执僵化致恒反成蔽。",
    businessGuidance: "稳健经营、长期复利、品牌沉淀的持久战，利有攸往。",
    relationshipGuidance: "婚姻长久之道在恒，需彼此包容成长，非一味忍耐。",
    healthGuidance: "主肝胆风木、筋骨，宜恒常锻炼，忌三日打鱼。"
  },
  {
    number: 33,
    name: "天山遁",
    pinyin: "Tiān Shān Dùn",
    upperTrigram: "乾",
    lowerTrigram: "艮",
    symbol: "䷠",
    judgment: "遁，亨，小利贞。天下有山，远小人不恶而严。",
    image: "天下有山，退避保全，远小人，不恶而严。",
    tianjiContext: "《天纪》论遁卦：天下有山，遁也。阳当退避，小人渐长。君子远小人，不恶而严——不与之绝交树敌，而严于律己划清界限。",
    actionGuidance: "【以果决行】：察觉小人当道或时机不利，果断退避保全，明哲保身而非正面对抗。",
    businessGuidance: "行业周期见顶、避祸退出、优雅离场套现的时机。",
    relationshipGuidance: "感情中宜保持距离化解矛盾，不恶语相向而守界限。",
    healthGuidance: "主退养、呼吸系统，宜隐退静养，避世俗纷扰。"
  },
  {
    number: 34,
    name: "雷天大壮",
    pinyin: "Léi Tiān Dà Zhuàng",
    upperTrigram: "震",
    lowerTrigram: "乾",
    symbol: "䷡",
    judgment: "大壮，利贞。雷在天上，非礼弗履。",
    image: "雷在天上，阳刚壮盛，壮勿妄动，非礼弗履。",
    tianjiContext: "《天纪》论大壮：雷在天上，大壮也。阳刚壮盛，然壮而妄动必败。君子以非礼弗履——壮时更须守礼节制，不可恃强凌弱。",
    actionGuidance: "【以果决行】：实力雄厚时宜乘势进取，但严守规矩底线，恃强妄为必招凶。",
    businessGuidance: "企业强势扩张、资本雄厚的进攻期，但合规为第一要务。",
    relationshipGuidance: "感情中男方强势时需以礼相待，尊重对方，强扭瓜不甜。",
    healthGuidance: "主筋骨强壮、阳气过旺，宜泄有余，防血压亢奋。"
  },
  {
    number: 35,
    name: "火地晋",
    pinyin: "Huǒ Dì Jìn",
    upperTrigram: "离",
    lowerTrigram: "坤",
    symbol: "䷢",
    judgment: "晋，康侯用锡马蕃庶，昼日三接。明出地上，自昭明德。",
    image: "明出地上，晋升光明，自昭明德，受宠渐进。",
    tianjiContext: "《天纪》论晋卦：明出地上，晋也。进而丽乎大明，如康侯之受宠。君子以自昭明德——自强不息彰明己德，自然晋升。",
    actionGuidance: "【以果决行】：事业上升期宜主动展现才能、争取认可，凭实力光明正大，不靠钻营。",
    businessGuidance: "升职加薪、品牌曝光、市场拓展的顺风期，昼日三接。",
    relationshipGuidance: "感情地位提升、被家庭认可，宜自昭其德。",
    healthGuidance: "主心火光明、视力，宜舒展阳气，防郁火内焚。"
  },
  {
    number: 36,
    name: "地火明夷",
    pinyin: "Dì Huǒ Míng Yí",
    upperTrigram: "坤",
    lowerTrigram: "离",
    symbol: "䷣",
    judgment: "明夷，利艰贞。明入地中，用晦而明。",
    image: "明入地中，光明受伤，韬光养晦，用晦而明。",
    tianjiContext: "《天纪》论明夷：明入地中，明夷也。光明受损、贤人遭难。君子以莅众用晦而明——外示柔暗、内存光明，韬光养晦以待时。",
    actionGuidance: "【以果决行】：身处打压暗算之境，切勿显露锋芒，外柔内刚、忍辱负重以保全。",
    businessGuidance: "行业寒冬、被排挤打压时，宜低调保身、暗中布局。",
    relationshipGuidance: "感情受委屈时隐忍沟通，不用晦暗之怒激化。",
    healthGuidance: "主心火被抑、抑郁之疾，宜疏肝解郁，防闷出大病。"
  },
  {
    number: 37,
    name: "风火家人",
    pinyin: "Fēng Huǒ Jiā Rén",
    upperTrigram: "巽",
    lowerTrigram: "离",
    symbol: "䷤",
    judgment: "家人，利女贞。风自火出，言有物行有恒。",
    image: "风自火出，齐家治国，言有物行有恒。",
    tianjiContext: "《天纪》论家人：风自火出，家人也。家道之正则天下定。君子以言有物而行有恒——家人严而有则，女正则家齐。",
    actionGuidance: "【以果决行】：先齐其家、立规矩，言行一致作表率，家齐而后可谋外。",
    businessGuidance: "家族企业、内部治理、团队文化建设的关键，利女贞（重诚信稳固）。",
    relationshipGuidance: "婚姻家庭的经营之本，各正其位、言出必行。",
    healthGuidance: "主心火与风气，家和则身心安泰，忌内耗致病。"
  },
  {
    number: 38,
    name: "火泽睽",
    pinyin: "Huǒ Zé Kuí",
    upperTrigram: "离",
    lowerTrigram: "兑",
    symbol: "䷥",
    judgment: "睽，小事吉。上火下泽，同而异。",
    image: "上火下泽，乖离背反，求同存异，小事可成。",
    tianjiContext: "《天纪》论睽卦：上火下泽，睽也。二女同居志不同，乖离背反之时。然天地睽而其事同，君子以同而异——求大同存小异。",
    actionGuidance: "【以果决行】：众人离心、意见相左时，不强行统一，求同存异、抓小事契机破局。",
    businessGuidance: "团队分歧、合作方理念冲突，宜先从小共识切入，小事吉。",
    relationshipGuidance: "夫妻观念差异大，宜包容差异、抓共同利益，勿强求一致。",
    healthGuidance: "主目疾、上火气滞，宜疏解情绪，防因气致病。"
  },
  {
    number: 39,
    name: "水山蹇",
    pinyin: "Shuǐ Shān Jiǎn",
    upperTrigram: "坎",
    lowerTrigram: "艮",
    symbol: "䷦",
    judgment: "蹇，利西南，不利东北。利见大人，贞吉。山上有水，反身修德。",
    image: "山上有水，蹇难在前，反身修德，见大人济。",
    tianjiContext: "《天纪》论蹇卦：山上有水，蹇也。蹇者难也，行险阻而前。君子以反身修德——遇难不怨天尤人，反求诸己、修德待时。",
    actionGuidance: "【以果决行】：前路险阻，不可强行，宜退而修身积德、求明师指点（见大人）方济。",
    businessGuidance: "项目遇阻、市场不利，宜收缩反思、借力权威，不利冒进东北（扩张）。",
    relationshipGuidance: "感情遇冷时先反省自身，修德以待转机。",
    healthGuidance: "主关节痹阻、腰膝水湿，宜保暖祛湿，防旧伤复发。"
  },
  {
    number: 40,
    name: "雷水解",
    pinyin: "Léi Shuǐ Xiè",
    upperTrigram: "震",
    lowerTrigram: "坎",
    symbol: "䷧",
    judgment: "解，利西南，无所往其来复吉，有攸往夙吉。雷雨作，赦过宥罪。",
    image: "雷雨作解，险难消解，赦过宥罪，夙吉。",
    tianjiContext: "《天纪》论解卦：雷雨作，解也。险以动，动而免乎险。君子以赦过宥罪——危机甫解，宜宽恕过往、轻装前进，夙吉（早行动）。",
    actionGuidance: "【以果决行】：困局刚解，迅速行动（夙吉）抓住喘息之机，既往不咎、向前看。",
    businessGuidance: "危机解除后的复苏期，宜快速重启业务、赦免内部过错。",
    relationshipGuidance: "矛盾化解后翻篇向前，不翻旧账，关系回暖。",
    healthGuidance: "主舒缓放松、筋骨舒展，雨后得舒，宜适度活动。"
  },
  {
    number: 41,
    name: "山泽损",
    pinyin: "Shān Zé Sǔn",
    upperTrigram: "艮",
    lowerTrigram: "兑",
    symbol: "䷨",
    judgment: "损，有孚，元吉，无咎，可贞，利有攸往。山下有泽，惩忿窒欲。",
    image: "山下有泽，损下益上，惩忿窒欲，先难后易。",
    tianjiContext: "《天纪》论损卦：山下有泽，损也。损刚益柔，损下益上。君子以惩忿窒欲——减损私欲忿怒，先难后易，终获元吉。",
    actionGuidance: "【以果决行】：主动削减不必要开支与欲望、克制情绪，先苦后甘，利有攸往。",
    businessGuidance: "降本增效、砍掉亏损业务、节制扩张的收缩优化期。",
    relationshipGuidance: "感情中克制脾气、少计较，损己益彼反得长久。",
    healthGuidance: "主减损瘀滞、节制饮食，惩忿窒欲最利养生。"
  },
  {
    number: 42,
    name: "风雷益",
    pinyin: "Fēng Léi Yì",
    upperTrigram: "巽",
    lowerTrigram: "震",
    symbol: "䷩",
    judgment: "益，利有攸往，利涉大川。风雷，见善则迁有过则改。",
    image: "风雷相助，益下损上，迁善改过，惠而不费。",
    tianjiContext: "《天纪》论益卦：风雷，益也。损上益下，民悦无疆。君子以见善则迁、有过则改——损上（特权）益下（大众），上下俱益。",
    actionGuidance: "【以果决行】：利他共赢、惠泽团队与客户，见善即迁、有过即改，利涉大川。",
    businessGuidance: "让利促销、股权激励、普惠模式，益人者自益。",
    relationshipGuidance: "感情中互相成就、彼此增益，施比受更有福。",
    healthGuidance: "主风气疏散、增益元气，宜行善积德以养身。"
  },
  {
    number: 43,
    name: "泽天夬",
    pinyin: "Zé Tiān Guài",
    upperTrigram: "兑",
    lowerTrigram: "乾",
    symbol: "䷪",
    judgment: "夬，扬于王庭，孚号有厉，告自邑，不利即戎，利有攸往。泽上于天，施禄及下。",
    image: "泽上于天，决去小人，刚决而和，施禄及下。",
    tianjiContext: "《天纪》论夬卦：泽上于天，夬也。决也，刚决柔也。扬于王庭、孚号有厉——公开决裂小人，但以正道刚决而和，不宜武力（不利即戎）。",
    actionGuidance: "【以果决行】：清理害群之马须公开公正、依理依法，果断而留余地，不赶尽杀绝。",
    businessGuidance: "清退劣质合作方、公开维权，刚毅果决但留退路。",
    relationshipGuidance: "感情中决断分手或划清界限，宜干脆不留纠缠。",
    healthGuidance: "主决断宣泄、上焦火旺，宜宣泄有度，防急躁伤身。"
  },
  {
    number: 44,
    name: "天风姤",
    pinyin: "Tiān Fēng Gòu",
    upperTrigram: "乾",
    lowerTrigram: "巽",
    symbol: "䷫",
    judgment: "姤，女壮，勿用取女。天下有风，施命诰四方。",
    image: "天下有风，不期而遇，阴长侵阳，防微杜渐。",
    tianjiContext: "《天纪》论姤卦：天下有风，姤也。柔遇刚也，不期而遇。一阴始生侵阳，女壮勿取——意外之遇须警惕，防小人阴长。",
    actionGuidance: "【以果决行】：突如其来的机遇或桃花，须冷静甄别，防阴柔小人乘虚而入，勿轻率接纳。",
    businessGuidance: "意外合作/机遇暗藏风险，宜审慎尽调，不盲目联姻。",
    relationshipGuidance: "露水姻缘、不正桃花卦，女壮勿取，防纠缠伤身。",
    healthGuidance: "主阴邪入侵、妇科隐疾，宜洁身自好，防暗疾。"
  },
  {
    number: 45,
    name: "泽地萃",
    pinyin: "Zé Dì Cuì",
    upperTrigram: "兑",
    lowerTrigram: "坤",
    symbol: "䷬",
    judgment: "萃，亨。王假有庙，利见大人，用大牲吉。泽上于地，除戎器戒不虞。",
    image: "泽上于地，荟萃聚集，聚人以正，戒备不虞。",
    tianjiContext: "《天纪》论萃卦：泽上于地，萃也。万物荟萃，聚以正也。王假有庙、利见大人——聚合人心须有核心信仰与明主，且除戎器戒不虞。",
    actionGuidance: "【以果决行】：聚众成事须立正道核心、拥戴明主，同时常备戒心防内乱。",
    businessGuidance: "社群裂变、平台聚量、团建凝聚的红利期，但防内部分裂。",
    relationshipGuidance: "家庭/感情聚首团圆吉，需共同价值观为基。",
    healthGuidance: "主聚合壅滞、脾胃积湿，宜疏散运动，防聚会贪食。"
  },
  {
    number: 46,
    name: "地风升",
    pinyin: "Dì Fēng Shēng",
    upperTrigram: "坤",
    lowerTrigram: "巽",
    symbol: "䷭",
    judgment: "升，元亨，用见大人，勿恤，南征吉。地中生木，顺德积小高大。",
    image: "地中生木，柔顺上升，积小成高，南征大吉。",
    tianjiContext: "《天纪》论升卦：地中生木，升也。巽而顺，刚中而应。君子以顺德积小以高大——柔顺积德，由小至大，勿忧恤而向南进取。",
    actionGuidance: "【以果决行】：踏实积累、顺势而上，不忧不惧，积小成大，南征（进取）吉。",
    businessGuidance: "稳步成长、口碑积累、向上突破的上升通道，勿恤而进。",
    relationshipGuidance: "感情/家庭地位渐入佳境，柔顺积累终升。",
    healthGuidance: "主木气升发、肝胆条达，宜舒展情志，防郁滞。"
  },
  {
    number: 47,
    name: "泽水困",
    pinyin: "Zé Shuǐ Kùn",
    upperTrigram: "兑",
    lowerTrigram: "坎",
    symbol: "䷮",
    judgment: "困，亨，贞，大人吉，无咎。有言不信。泽无水，致命遂志。",
    image: "泽中无水，困穷守正，致命遂志，言不信时。",
    tianjiContext: "《天纪》论困卦：泽无水，困也。困而不失其所亨，其唯君子乎。致命遂志——处困穷而守正不移，虽言不见信，志不可夺。",
    actionGuidance: "【以果决行】：陷入绝境时宁守正受困，不曲道求脱；致命遂志，等待困极而通。",
    businessGuidance: "资金枯竭、四面楚歌期，宜壮士断腕守志，不乱求救。",
    relationshipGuidance: "感情困顿中守忠诚，不轻信流言，困而亨。",
    healthGuidance: "主肾水枯竭、精气亏虚，宜静养固本，防虚脱。"
  },
  {
    number: 48,
    name: "水风井",
    pinyin: "Shuǐ Fēng Jǐng",
    upperTrigram: "坎",
    lowerTrigram: "巽",
    symbol: "䷯",
    judgment: "井，改邑不改井，无丧无得，往来井井。木上有水，劳民劝相。",
    image: "木上有水，井养不穷，养人恒德，勿竭其源。",
    tianjiContext: "《天纪》论井卦：木上有水，井也。井养而不穷，改邑不改井。君子以劳民劝相——惠泽恒久、养人养德，但井甃须洁，羸瓶则凶。",
    actionGuidance: "【以果决行】：建立可持续的滋养体系（人才/客户/资源），源源惠人，但须维护根本不失。",
    businessGuidance: "会员制、复购模型、基础设施等长期养用户之业，往来井井。",
    relationshipGuidance: "感情如井，恒养不竭，互相滋养最稳固。",
    healthGuidance: "主肾水滋养、代谢循环，宜补水润燥，忌竭泽而渔。"
  },
  {
    number: 49,
    name: "泽火革",
    pinyin: "Zé Huǒ Gé",
    upperTrigram: "兑",
    lowerTrigram: "离",
    symbol: "䷰",
    judgment: "革，巳日乃孚，元亨利贞，悔亡。泽中有火，治历明时。",
    image: "泽中有火，变革更化，顺天应人，巳日乃孚。",
    tianjiContext: "《天纪》论革卦：泽中有火，革也。汤武革命，顺乎天而应乎人。巳日乃孚——变革须待时机成熟、取信于众，元亨利贞。",
    actionGuidance: "【以果决行】：推动彻底变革须先凝聚共识、择时而动，顺天应人方无悔亡。",
    businessGuidance: "转型重构、换赛道、组织革命的关键期，巳日（时机）乃孚。",
    relationshipGuidance: "感情/关系的根本性改变须双方共识，强行必裂。",
    healthGuidance: "主新陈代谢、火水相激，宜顺势调理，防骤变伤身。"
  },
  {
    number: 50,
    name: "火风鼎",
    pinyin: "Huǒ Fēng Dǐng",
    upperTrigram: "离",
    lowerTrigram: "巽",
    symbol: "䷱",
    judgment: "鼎，元吉，亨。木上有火，正位凝命。",
    image: "木上有火，鼎新烹饪，正位凝命，王者之器。",
    tianjiContext: "《天纪》论鼎卦：木上有火，鼎也。鼎者器也，烹饪以享上帝、养圣贤。君子以正位凝命——端正本位、凝聚天命使命，元吉。",
    actionGuidance: "【以果决行】：确立核心使命与地位（正位凝命），以鼎盛之器承载大业，元吉亨通。",
    businessGuidance: "树立品牌使命、核心团队就位、产品立鼎的奠基期。",
    relationshipGuidance: "家庭中正位（父严母慈）各司其职，家道乃兴。",
    healthGuidance: "主鼎养脾胃、温补元气，宜食养正位，忌寒凉。"
  },
  {
    number: 51,
    name: "震为雷",
    pinyin: "Zhèn Wéi Léi",
    upperTrigram: "震",
    lowerTrigram: "震",
    symbol: "䷲",
    judgment: "震，亨。震来虩虩，笑言哑哑；震惊百里，不丧匕鬯。洊雷，恐惧修省。",
    image: "洊雷相继，震动惊惧，修省谨慎，不丧其器。",
    tianjiContext: "《天纪》论震卦：洊雷，震也。震来虩虩、笑言哑哑——临大震惧而能镇定自若。君子以恐惧修省——敬畏谨慎、反身修德。",
    actionGuidance: "【以果决行】：面对突发巨震（危机/变故），临危不乱、镇定应对，且因惧而修省。",
    businessGuidance: "行业震荡、黑天鹅事件中，稳心神者反获机会（震惊百里不丧匕鬯）。",
    relationshipGuidance: "感情突遭冲击时镇定沟通，慌乱最伤关系。",
    healthGuidance: "主肝胆雷火、惊悸，宜安神定志，防受惊致病。"
  },
  {
    number: 52,
    name: "艮为山",
    pinyin: "Gèn Wéi Shān",
    upperTrigram: "艮",
    lowerTrigram: "艮",
    symbol: "䷳",
    judgment: "艮其背，不获其身，行其庭，不见其人，无咎。兼山，思不出其位。",
    image: "兼山为艮，止其所止，思不出位，动静有时。",
    tianjiContext: "《天纪》论艮卦：兼山，艮也。艮其背，止也。时止则止、时行则行，动静不失其时。君子以思不出其位——安分守己、止于所当止。",
    actionGuidance: "【以果决行】：该停手时果断止步、安于本位，不妄动越界，止而乃吉。",
    businessGuidance: "止盈收手、守住核心业务、不盲目多元化的稳守期。",
    relationshipGuidance: "感情中知止不纠缠，各安其位最和睦。",
    healthGuidance: "主静止安神、脾胃安居，宜静坐止念，防思虑过度。"
  },
  {
    number: 53,
    name: "风山渐",
    pinyin: "Fēng Shān Jiàn",
    upperTrigram: "巽",
    lowerTrigram: "艮",
    symbol: "䷴",
    judgment: "渐，女归吉，利贞。山上有木，居贤德善俗。",
    image: "山上有木，循序渐进，女归以渐，善俗成德。",
    tianjiContext: "《天纪》论渐卦：山上有木，渐也。木生于山，长则高矣。渐者进也，以序而进。女归吉——如女子出嫁，循序渐进方吉。",
    actionGuidance: "【以果决行】：事业感情皆宜按部就班、循序渐进，不可躐等冒进，渐则有功。",
    businessGuidance: "产品迭代、市场渗透、人才培养的稳步渐进期，女归吉。",
    relationshipGuidance: "婚姻感情宜按节奏发展，闪婚躐等易悔，渐则吉。",
    healthGuidance: "主木气渐长、肝胆舒缓，宜缓调慢养，忌峻补。"
  },
  {
    number: 54,
    name: "雷泽归妹",
    pinyin: "Léi Zé Guī Mèi",
    upperTrigram: "震",
    lowerTrigram: "兑",
    symbol: "䷵",
    judgment: "归妹，征凶，无攸利。泽上有雷，永终知敝。",
    image: "泽上有雷，归妹失正，征则凶险，永终知敝。",
    tianjiContext: "《天纪》论归妹：泽上有雷，归妹也。归妹征凶，无攸利。男女之终始也，然以悦而动、失夫妇之正。君子以永终知敝——知其弊而慎终。",
    actionGuidance: "【以果决行】：动机不纯的结合或合作（悦而动、失正），冒进必凶，须慎察其敝。",
    businessGuidance: "看似诱人的并购/联姻暗藏失衡，征凶无攸利，宜三思。",
    relationshipGuidance: "不以正道结合的感情（闪婚、功利联姻）多凶，永终知敝。",
    healthGuidance: "主悦动失节、妇科失调，宜守正养生，防纵欲。"
  },
  {
    number: 55,
    name: "雷火丰",
    pinyin: "Léi Huǒ Fēng",
    upperTrigram: "震",
    lowerTrigram: "离",
    symbol: "䷶",
    judgment: "丰，亨，王假之，勿忧，宜日中。雷电皆至，折狱致刑。",
    image: "雷电皆至，丰大盛满，日中则昃，折狱致刑。",
    tianjiContext: "《天纪》论丰卦：雷电皆至，丰也。丰者大也，盛大满盈。宜日中——如日当中天，然日中则昃、月盈则食，盛极须防衰。",
    actionGuidance: "【以果决行】：事业鼎盛期大展宏图，但居安思危、宜日中（把握顶点），防盛极而衰。",
    businessGuidance: "企业巅峰、名利双收期，宜乘势固化成果，折狱致刑（整顿秩序）。",
    relationshipGuidance: "感情浓烈如日中，需珍惜当下，防盛极转疏。",
    healthGuidance: "主心火亢盛、丰盈过满，宜清润泄火，防暴喜伤身。"
  },
  {
    number: 56,
    name: "火山旅",
    pinyin: "Huǒ Shān Lǚ",
    upperTrigram: "离",
    lowerTrigram: "艮",
    symbol: "䷷",
    judgment: "旅，小亨，旅贞吉。山上有火，明慎用刑不留狱。",
    image: "山上有火，行旅在外，明慎柔顺，旅贞乃吉。",
    tianjiContext: "《天纪》论旅卦：山上有火，旅也。旅者羁旅，身寄他乡。君子以明慎用刑而不留狱——行旅在外须明察谨慎、柔顺待人，不滞留是非。",
    actionGuidance: "【以果决行】：漂泊变动、客居他乡时，宜明慎柔顺、速决速行，不深陷是非。",
    businessGuidance: "异地拓展、出差驻外、短期项目的过渡期，旅贞吉。",
    relationshipGuidance: "异地恋或关系漂泊期，明慎沟通、不留隐患。",
    healthGuidance: "主奔波劳顿、火气外浮，宜安定作息，防旅途耗损。"
  },
  {
    number: 57,
    name: "巽为风",
    pinyin: "Xùn Wéi Fēng",
    upperTrigram: "巽",
    lowerTrigram: "巽",
    symbol: "䷸",
    judgment: "巽，小亨，利有攸往，利见大人。随风，申命行事。",
    image: "随风巽顺，谦逊申命，柔入刚中，小亨有往。",
    tianjiContext: "《天纪》论巽卦：随风，巽也。巽者入也、顺也。君子以申命行事——谦逊顺从、反复申明政令，柔能入刚，小亨而利往。",
    actionGuidance: "【以果决行】：以谦逊顺势、反复沟通（申命）推进事务，柔中带刚，利见大人。",
    businessGuidance: "公关协调、政策沟通、以柔克刚的渗透期，小亨利往。",
    relationshipGuidance: "感情中以柔顺随和化解对立，申命（表达）而不强。",
    healthGuidance: "主风气入里、肝胆条达，宜舒缓顺气，防郁逆。"
  },
  {
    number: 58,
    name: "兑为泽",
    pinyin: "Duì Wéi Zé",
    upperTrigram: "兑",
    lowerTrigram: "兑",
    symbol: "䷹",
    judgment: "兑，亨，利贞。丽泽，朋友讲习。",
    image: "丽泽相连，悦兑相欢，朋友讲习，利贞而亨。",
    tianjiContext: "《天纪》论兑卦：丽泽，兑也。兑者说（悦）也。君子以朋友讲习——上下交悦、朋来讲习，和悦而守正（利贞）方吉。",
    actionGuidance: "【以果决行】：以诚信和悦待人、凝聚同好讲习共进，但悦须合正道，谄悦则凶。",
    businessGuidance: "社群运营、口碑传播、愉悦消费体验的利好期，朋友讲习。",
    relationshipGuidance: "感情愉悦和乐、朋友式相处最滋养，忌巧言令色。",
    healthGuidance: "主肺金润泽、气道舒畅，宜欢悦养肺，防忧悲伤肺。"
  },
  {
    number: 59,
    name: "风水涣",
    pinyin: "Fēng Shuǐ Huàn",
    upperTrigram: "巽",
    lowerTrigram: "坎",
    symbol: "䷺",
    judgment: "涣，亨。王假有庙，利涉大川，利贞。风行水上，享帝立庙。",
    image: "风行水上，涣散而通，聚神凝心，涉川乃利。",
    tianjiContext: "《天纪》论涣卦：风行水上，涣也。涣者散也，然散中有聚。王假有庙——涣散之时须立宗庙聚合人心、享于上帝，方转散为聚。",
    actionGuidance: "【以果决行】：团队涣散、人心浮动时，须重塑共同信仰与目标（立庙），凝聚后利涉大川。",
    businessGuidance: "组织涣散、用户流失期，宜重筑文化内核与愿景，转涣为聚。",
    relationshipGuidance: "感情疏离时重塑共同记忆与目标，涣而能聚。",
    healthGuidance: "主风水涣散、气机外浮，宜收敛固表，防散泄亏虚。"
  },
  {
    number: 60,
    name: "水泽节",
    pinyin: "Shuǐ Zé Jié",
    upperTrigram: "坎",
    lowerTrigram: "兑",
    symbol: "䷻",
    judgment: "节，亨。苦节不可贞。泽上有水，制数度议德行。",
    image: "泽上有水，节制有度，数度合礼，苦节则凶。",
    tianjiContext: "《天纪》论节卦：泽上有水，节也。节以制度，不伤财不害民。君子以制数度议德行——节制合宜则亨，苦节（过度）不可贞。",
    actionGuidance: "【以果决行】：凡事节制有度、立制度数度，但过苛之苦节反凶，中道为吉。",
    businessGuidance: "预算管控、合规风控、节度扩张的稳健期，制数度。",
    relationshipGuidance: "感情中分寸节制最宜，过紧（苦节）则压抑生变。",
    healthGuidance: "主水泽节制、代谢有度，宜节饮食节欲，防壅滞。"
  },
  {
    number: 61,
    name: "风泽中孚",
    pinyin: "Fēng Zé Zhōng Fú",
    upperTrigram: "巽",
    lowerTrigram: "兑",
    symbol: "䷼",
    judgment: "中孚，豚鱼吉，利涉大川，利贞。泽上有风，议狱缓死。",
    image: "泽上有风，中孚诚信，豚鱼格神，议狱缓死。",
    tianjiContext: "《天纪》论中孚：泽上有风，中孚也。孚者信也，中心诚信，虽豚鱼（微物）亦可感格。君子以议狱缓死——以诚心恤囚、慎刑。",
    actionGuidance: "【以果决行】：以中心至诚待人处事，诚信可格豚鱼，利涉大川；亦宜宽厚慎断（议狱缓死）。",
    businessGuidance: "品牌建设信任、契约精神、口碑致胜的诚信期，豚鱼吉。",
    relationshipGuidance: "感情以诚相待、互不欺瞒，中孚之信最牢。",
    healthGuidance: "主诚信养心、风泽调和，宜诚中养神，防疑诈伤身。"
  },
  {
    number: 62,
    name: "雷山小过",
    pinyin: "Léi Shān Xiǎo Guò",
    upperTrigram: "震",
    lowerTrigram: "艮",
    symbol: "䷽",
    judgment: "小过，亨，利贞，可小事不可大事。飞鸟遗音，不宜上宜下。山上有雷，行过乎恭。",
    image: "山上有雷，小有过越，宜下不宜上，飞鸟遗音。",
    tianjiContext: "《天纪》论小过：山上有雷，小过也。有其信者必行之，故受之以小过。可小事不可大事，不宜上宜下——小有过失、谦下守分乃吉。",
    actionGuidance: "【以果决行】：小事可稍越常规（小过），但大事不可妄动，宜谦下不宜高攀，飞鸟遗音宜下。",
    businessGuidance: "细节微调、小事灵活可过，重大扩张决策不宜，守分为吉。",
    relationshipGuidance: "感情中谦下、小过（包容小错）最稳，不宜强出头。",
    healthGuidance: "主雷动小过、关节微疾，宜静养微调，防小患成大。"
  },
  {
    number: 63,
    name: "水火既济",
    pinyin: "Shuǐ Huǒ Jì Jì",
    upperTrigram: "坎",
    lowerTrigram: "离",
    symbol: "䷾",
    judgment: "亨小，利贞。初吉终乱。思患而预防之。",
    image: "水在火上，水火相交，烹饪调和，事已大成。",
    tianjiContext: "《天纪》论既济：六爻皆当位，完美之象。但‘初吉终乱’，万物盛极必衰，大成之后必须未雨绸缪，建立长效风控机制以防逆转。",
    actionGuidance: "【以果决行】：见好即收，巩固既得成果；居安思危，严查漏洞，不可骄奢自满。",
    businessGuidance: "项目圆满交付或盈利达标，宜落袋为安，规划下一阶段战略。",
    relationshipGuidance: "感情稳定圆满，需注重长久平淡生活中的情感保鲜。",
    healthGuidance: "心肾相交，水火既济，乃健康之最高境界，宜保持作息节律。",
  },
  {
    number: 64,
    name: "火水未济",
    pinyin: "Huǒ Shuǐ Wèi Jì",
    upperTrigram: "离",
    lowerTrigram: "坎",
    symbol: "䷿",
    judgment: "亨，小狐汔济，濡其尾，无攸利。慎辨物居方。",
    image: "火在水上，互不相融，事未成功，充满生机与转机。",
    tianjiContext: "《天纪》论未济：未济乃易经六十四卦最后一卦，也是新周期的开始。虽未成功，但蕴含无限可能。只要慎终如始，破局就在眼前。",
    actionGuidance: "【以果决行】：处于破晓前的关键时刻，咬紧牙关坚持最后一步，严谨打磨细节。",
    businessGuidance: "转型重组期，充满新赛道机会，做好风控迎接爆发。",
    relationshipGuidance: "好事多磨，彼此仍在磨合期，真诚沟通可跨越隔阂。",
    healthGuidance: "心火上炎而肾水不足，宜滋阴降火，保证充足睡眠。",
  },
];

export function getFullHexagramList(): HexagramData[] {
  return ALL_64_HEXAGRAMS_BRIEF;
}

// 基于四柱八字洛书算法推算天纪先天元神卦与后天更革卦
export function calculateTianjiNatalIChing(
  yearStem: HeavenlyStem,
  yearBranch: EarthlyBranch,
  monthStem: HeavenlyStem,
  monthBranch: EarthlyBranch,
  dayStem: HeavenlyStem,
  dayBranch: EarthlyBranch,
  hourStem: HeavenlyStem,
  hourBranch: EarthlyBranch,
  gender: Gender,
  lunarMonth: number
): {
  numerology: FourPillarsNumerology;
  preNatalDetail: HexagramData | null;
  postNatalDetail: HexagramData | null;
  renjianDaoPre: any | null;
  renjianDaoPost: any | null;
} {
  const numerology = calculateTianjiNumerology(
    yearStem,
    yearBranch,
    monthStem,
    monthBranch,
    dayStem,
    dayBranch,
    hourStem,
    hourBranch,
    gender,
    lunarMonth
  );

  const preDetail = ALL_64_HEXAGRAMS_BRIEF.find((h) => h.name === numerology.preNatalHexagram) || {
    number: 1,
    name: numerology.preNatalHexagram,
    pinyin: "",
    upperTrigram: numerology.upperTrigramPre,
    lowerTrigram: numerology.lowerTrigramPre,
    symbol: numerology.preNatalSymbol,
    judgment: "先天受命之卦，以象观心，以果决行。",
    image: "天道运行，生生不息。",
    tianjiContext: `《天纪》先天命卦【${numerology.preNatalHexagram}】，元堂动爻在第【${numerology.yuanTangYao}】爻，总管前【${numerology.preNatalYears}】年大运。`,
    actionGuidance: `当前先天命卦主轴，宜明察元堂动爻之吉凶，顺天应人。`,
    businessGuidance: "因势利导，明辨时机进退。",
    relationshipGuidance: "阴阳相济，守正道方得长久。",
    healthGuidance: "形神合一，修身养性。",
  };

  const postDetail = ALL_64_HEXAGRAMS_BRIEF.find((h) => h.name === numerology.postNatalHexagram) || {
    number: 11,
    name: numerology.postNatalHexagram,
    pinyin: "",
    upperTrigram: "坤",
    lowerTrigram: "乾",
    symbol: numerology.postNatalSymbol,
    judgment: "后天更革之卦，天旋地转，事乃大成。",
    image: "地气上升，天气下降，变化无穷。",
    tianjiContext: `《天纪》后天运卦【${numerology.postNatalHexagram}】，总管后【${numerology.postNatalYears}】年转革运势。`,
    actionGuidance: "顺应后天大运之气数转化，移星换斗，突破局限。",
    businessGuidance: "把握中晚年转型契机，守成创新并重。",
    relationshipGuidance: "沉淀心性，家和万事兴。",
    healthGuidance: "注重后天脾胃与元气调摄。",
  };

  const renjianDaoPre = getRenjianDaoDetail(numerology.preNatalHexagram);
  const renjianDaoPost = getRenjianDaoDetail(numerology.postNatalHexagram);

  return {
    numerology,
    preNatalDetail: preDetail,
    postNatalDetail: postDetail,
    renjianDaoPre,
    renjianDaoPost,
  };
}
